name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SD_TestAutomationFramework/SD_TestAutomationFramework.sln
    - name: Build
      run: dotnet build --no-restore SD_TestAutomationFramework/SD_TestAutomationFramework.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal SD_TestAutomationFramework/SD_TestAutomationFramework.sln
